Major update of /lib/smartdc for Linux
As of this update this works for Ubuntu and Debian systems

debian-powerbtn-acpi-support.sh - called by apic to log API called shutdowns
disable-iptables - uses Mdata to clear IP tables on boot
format-secondary-disk - enhaced logging and formatting of /data disk
get-motd - gets alert\info\tip info from Joyent MOTD server
joyent_dataset_changelog - place for dataset changes to be placed
joyent_linux_repo_gpg_key - GPG key used for Joyent Linux Repos
joyent_motd_footer - dynamic MOTD with system checks and custom messages
joyent_product_info - Joyent product information
joyent_rc.local - Joyent specific rc.local ( called from /etc/rc.local )
joyent_version - dataset version info used by other scripts in /lib/smartdc
lib_smartdc_scripts.cfg - common variables and functions used by scripts in /lib/smartdc
mdata-get - minor changes only
prepare-image - lots of changes and QA checks
remove_unused_kernels - keeps datasize down by removing unused kernels
run-user-script - added Mdata check to run user-script on each boot
send-arp-updates - minor changes - mainly logging
set-hostname - added Mdata check to set hostname via API - is called via /sbin/dhclient-script
set-root-authorized-keys - added Mdata check to allow customer to reload root auth keys

This is a major update and new changes to scripts will us this git repo
for better management and change control

diff --git a/src/linux/lib/smartdc/mdata-get b/src/linux/lib/smartdc/mdata-get
--- a/src/linux/lib/smartdc/mdata-get
+++ b/src/linux/lib/smartdc/mdata-get
@@ -1,4 +1,4 @@
-#!/bin/bash
+#! /bin/bash
 #
 # Copyright (c) 2011 Joyent Inc., All rights reserved.
 #
@@ -13,88 +13,108 @@
 # 3 - invalid usage
 #
 
-#set -o xtrace
+# load common functions and vars
+. /lib/smartdc/lib_smartdc_scripts.cfg
+
+# NOTE: do not use lib_smartdc_fatal here as it will exit 1
+#       use lib_smartdc_info instead and let this script
+#       exit with own codes
+
+if [ $DEBUG -gt 5 ]; then
+  set -o xtrace
+fi
 
 key=$1
 if [[ -z ${key} ]]; then
-  echo "Usage: $0 <key>" >&2
-  exit 3
+    lib_smartdc_info "ERROR: $0 called without a key"
+    echo "Usage: $0 <key>" >&2
+    echo " "
+    exit 3
 fi
 
 NC_SOCK=
 DISABLE_ECHO="yes"
 TIMEOUT=60
 
-case $(uname -s) in
-  Linux)
-    SERIAL_DEV="/dev/ttyS1"
+#case $(uname -s) in
+case `uname -s | tr '[:upper:]' '[:lower:]'` in
+    linux)
+        SERIAL_DEV="/dev/ttyS1"
+        if [ ! -e $SERIAL_DEV ]; then
+          lib_smartdc_info "ERROR: $SERIAL_DEV does not exist"
+        fi
     ;;
-  FreeBSD)
-		SERIAL_DEV="/dev/cuau1"
-		;;
-  SunOS)
-		NC_SOCK="/var/run/smartdc/metadata.sock"
-		DISABLE_ECHO="no"
-		;;
-  *)
-		echo "Don't know which serial to use for $(uname -s)" >&2
-		exit 3
-  ;;
+    freebsd)
+        SERIAL_DEV="/dev/cuau1"
+    ;;
+    sunos)
+        NC_SOCK="/var/run/smartdc/metadata.sock"
+        DISABLE_ECHO="no"
+    ;;
+    *)
+        lib_smartdc_info "ERROR: Don't know which serial to use for $(uname -s)"
+        #echo "Don't know which serial to use for $(uname -s)" >&2
+        exit 3
+    ;;
 esac
 
 if [[ -n ${NC_SOCK} ]]; then
-  coproc nc -U ${NC_SOCK}
-  exec <&${COPROC[0]} 3>&${COPROC[1]}
+    coproc nc -U ${NC_SOCK}
+    exec <&${COPROC[0]} 3>&${COPROC[1]}
 else
-  exec <${SERIAL_DEV} 3>>${SERIAL_DEV}
+    exec <${SERIAL_DEV} 3>>${SERIAL_DEV}
 fi
 
 IFS=$'\n'
 if [[ ${DISABLE_ECHO} == "yes" ]]; then
-  stty -echo
+    stty -echo
 fi
 
 got_all_data=0
 keep_trying=1
 while [[ ${keep_trying} -eq 1 ]]; do
-  echo "GET ${key}" >&3
-  result=""
+    echo "GET ${key}" >&3
+    result=""
 
-  # First line will be a status.
-  read -t ${TIMEOUT} status
-  retval=$?
-  if [[ ${retval} -gt 128 ]]; then
-		echo "mdata-get: timeout getting status. (exit code: ${retval})" >&2
-		continue
-  elif [[ ${retval} -ne 0 ]]; then
-		echo "mdata-get: failed to read data from metadata agent. (exit code: ${retval})" >&2
-		exit 2
-  fi
+    # First line will be a status.
+    read -t ${TIMEOUT} status
+    retval=$?
+    if [[ ${retval} -gt 128 ]]; then
+        lib_smartdc_info "mdata-get: timeout getting status. (exit code: ${retval})"
+        echo "mdata-get: timeout getting status. (exit code: ${retval})" >&2
+        continue
+    elif [[ ${retval} -ne 0 ]]; then
+        lib_smartdc_info "mdata-get: failed to read data from metadata agent. (exit code: ${retval})"
+        echo "mdata-get: failed to read data from metadata agent. (exit code: ${retval})" >&2
+        exit 2
+    fi
 
-  if [[ ${status} == "NOTFOUND" ]]; then
-		echo "No metadata for ${key}"
-		exit 1
-  elif [[ ${status} != "SUCCESS" ]]; then
-		echo "Error getting metadata for key ${key}: ${status}"
-		exit 2
-  fi
+    if [[ ${status} == "NOTFOUND" ]]; then
+        echo "No metadata for ${key}"
+        exit 1
+    elif [[ ${status} != "SUCCESS" ]]; then
+        lib_smartdc_info "Error getting metadata for key ${key}: ${status}"
+        echo "Error getting metadata for key ${key}: ${status}"
+        exit 2
+    fi
 
-  while read -t ${TIMEOUT} line; do
-  if [[ ${line} == "." ]]; then
-    # response is terminated by '.' on line by itself.
-    got_all_data=1
-    break;
-  fi
-  # If a line begins with a '.' it was escaped, remove that dot.
-  line="${line#.}\n"
-  result="${result}${line}"
-  keep_trying=0
-  done
+    while read -t ${TIMEOUT} line; do
+        if [[ ${line} == "." ]]; then
+            # response is terminated by '.' on line by itself.
+            got_all_data=1
+            break;
+        fi
+        # If a line begins with a '.' it was escaped, remove that dot.
+        line="${line#.}\n"
+        result="${result}${line}"
+        keep_trying=0
+    done
 done
 
 if [[ ${got_all_data} -ne 1 ]]; then
-   echo "mdata-get: error getting results. Please try again." >&2
-   exit 2
+     lib_smartdc_info "mdata-get: error getting results. Please try again."
+     echo "mdata-get: error getting results. Please try again." >&2
+     exit 2
 fi
 
 echo -n -e "${result}"
